### ISSUE TITLE
Sitemap not generated

### ISSUE THREAD

**Issue by Jaspur** [ecdeveloper/node-web-crawler#15]
When clicked to download the site map, you get `Cannot GET /sitemaps/`. 

In `public/sitemaps/sitemap_www.foobar.com.xml` the content is just one line:

```
1 <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>
```

**Comment by mhhansen** [comment]
what's the final url address that download link has?
regarding XML content, probably it's empty because the URL doesn't have any source code / content.

**Comment by Jaspur** [comment]
When I dump the content in the console of what should be in the site map, it does show up, but the .xml has only one line.

**Comment by ecdeveloper** [comment]
Fixed the issue in new version. Give it a try and let me know if the problem persists.
