### ISSUE TITLE
How do i also store the HTML content of the page?

### ISSUE THREAD

**Issue by peterbarretto** [ecdeveloper/node-web-crawler#4]
How do i also store the HTML content of the page?
What field type should i put for the field in which i store the html content?

**Comment by ecdeveloper** [comment]
You want to save the html of each page you parsed?

**Comment by peterbarretto** [comment]
Yes

**Comment by ecdeveloper** [comment]
Inside callback of make_request function you can access variable `body`, it contains the html of a page. To store it mongo, just add a field to your LinksGrabbedModel model with type String. Now the schema is defined like: 

``` javascript
new mongoose.Schema({url: { type: String, index: { unique: true }}, source: String, content_type: String, http_status: Number, depth_level: Number }
```

Change it to smth like: 

``` javascript
new mongoose.Schema({url: { type: String, index: { unique: true }}, source: String, content_type: String, http_status: Number, depth_level: Number, body: String }
```

**Comment by peterbarretto** [comment]
Made the above change and changed the below line in crawling-daemon.js  
        doc.body = body;
                doc.save();
